# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2019-02-26 08:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('content', models.CharField(max_length=1000)),
                ('image', models.ImageField(blank=True, null=True, upload_to='profile_image')),
            ],
        ),
    ]
